### ISSUE TITLE
Migrate the demo to the new debezium endpoint

### ISSUE THREAD

**Issue by omarsmak** [squakez/debezium-camel-demo#1]
@squakez we have changed the camel debezium endpoint, now we have separated each database onto its component, that means you will have an endpoint like this:
`debezium-<db>:<name>?`, please take a look here https://github.com/apache/camel/blob/master/components/camel-debezium-mysql/src/main/docs/debezium-mysql-component.adoc#uri-format

**Comment by squakez** [comment]
Thanks! I'll fix it right away!
